# Generated by Django 4.1.7 on 2023-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('member_id', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=20)),
                ('thumbnail', models.URLField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('member_pw', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('member_phone', models.CharField(max_length=20)),
                ('member_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
