# Generated by Django 4.1.7 on 2023-03-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='road',
            new_name='location',
        ),
    ]
